# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-06 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20171006_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='medicine_name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
