# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-31 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20171101_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='lowcountmedicinelist',
            name='low_count_medicine_id',
            field=models.CharField(default='MED000', max_length=8),
        ),
    ]
