# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-31 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_lowcountmedicinelist_low_count_medicine_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lowcountmedicinelist',
            name='low_count_medicine_id',
        ),
        migrations.RemoveField(
            model_name='lowcountmedicinelist',
            name='low_count_medicine_price',
        ),
    ]
