# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-31 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20171101_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='lowcountmedicinelist',
            name='message',
            field=models.CharField(default='', max_length=500),
        ),
    ]
