# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-31 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20171024_1836'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicineList',
        ),
    ]
